### ISSUE TITLE
Cannot access authentication server whithin docker

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-minecraft#11]
No idea why but  MC server is not able to authenticate with mojang/microsoft. Did not have issue when running outside docker.

**Comment by dudleycodes** [comment]
@JustinBenedick Please give me the information to repeat this condition, along with the exact error message you received.

**Comment by dudleycodes** [comment]
DNS being broken inside the container doesn't make any sense. It's just cgroups, Minecraft would have used the systems default gateway for DNS resolution.

Can you reproduce this problem? 

Is it possible it was a fluke? I.e., was the LAN having internet issues at the time this occurred, and then running it outside the Docker container just so happened to occur when the issue was resolved?

**Comment by dudleycodes** [comment]
@JustinBenedick - any updates? Were you able to reproduce?

**Comment by JustinBenedick** [comment]
unable to reproduce
